version: '2' 

services:
  ui:
    build: ui
    ports:
      - "4200:4200" 
    # restart: always

  projectService:
    build: projectService
    ports:
      - "3000:3000"
    links:
      - db 
    # restart: always
  feedService:
    build: feedService
    ports:
      - "3001:3001"
  db:
    image: mongo:3 
    ports:
      - "27017:27017" 
    # restart: always
