version: '2' 

services:
 ui:
    build: ui
    ports:
      - "4200:4200" 
    restart: always

 xena-backend:
    build: backend
    ports:
      - "8080:8080"
    links:
      - db 
    depends_on:
      - db
    restart: always
 db:
    image: mongo:3
    container_name: db 
    ports:
      - "27017:27017"